- name: "Requires NuGet.Core Change"
  color: "E10D60"
  description: "This issue requires a modification to something in referenced NuGet.Core library."
- name: "PowerShell Internal Host"
  color: "d4c5f9"
- name: "shimgen"
  color: "fbca04"
  description: "Issues related to shimgen"
- name: "Task"
  color: "006B75"
- name: "Package Issue"
  color: "eb6420"
  description: "Issues that are invalid for this repository, and is for packages that need to be fixed by a maintainer"
